# Generated by Django 5.2.2 on 2025-06-10 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myap", "0002_alter_product_buyer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyer",
            name="name",
        ),
        migrations.AddField(
            model_name="buyer",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="buyer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="myap.buyer",
            ),
            preserve_default=False,
        ),
    ]
